### ISSUE TITLE
Could you please integrate the new LaserTag environment into this project?

### ISSUE THREAD

**Issue by xiezhipeng-git** [deligentfool/DeepNash#1]
"I'm attempting to run this project, but I encountered a network error with torch.load. Therefore, I'd like to switch to the LaserTag-small3-v0 environment, as it supports rendering. However, I've noticed some issues with this environment in Gym version 0.26.2. I believe you have already made some updates. Could you please integrate the new LaserTag environment into this project?"

**Comment by deligentfool** [comment]
Hello, thank you for your interest in this project. I have updated the modified lasertag in the repository, and you can install it following the provided steps. Additionally, I have replaced the file storing the network, which now supports the lasertag environment. You can change the type of opponent agent in `opponent.py`. If you encounter any further issues, please don't hesitate to discuss them with me.

**Comment by deligentfool** [comment]
I'm going to close this issue now. Feel free to reach out again if you have any further questions or need assistance.
